# Generated by Django 4.2 on 2023-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=255)),
                ('feature_name', models.CharField(max_length=255)),
                ('feature_state', models.CharField(max_length=255)),
                ('assigned_user', models.CharField(max_length=255)),
                ('total_test_excuted', models.IntegerField()),
                ('test_passed', models.IntegerField()),
                ('test_failed', models.IntegerField()),
            ],
        ),
    ]
